// Get all tasks
export const GET_ALL_TASKS_REQUEST = 'GET_ALL_TASKS_REQUEST';
export const GET_ALL_TASKS_FAILED = 'GET_ALL_TASKS_FAILED';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';

// Get all completed tasks
export const GET_ALL_COMPLETED_TASKS_REQUEST = 'GET_ALL_COMPLETED_TASKS_REQUEST';
export const GET_ALL_COMPLETED_TASKS_FAILED = 'GET_ALL_COMPLETED_TASKS_FAILED';
export const GET_ALL_COMPLETED_TASKS_SUCCESS = 'GET_ALL_COMPLETED_TASKS_SUCCESS';

// Get all pending tasks
export const GET_ALL_PENDING_TASKS_REQUEST = 'GET_ALL_PENDING_TASKS_REQUEST';
export const GET_ALL_PENDING_TASKS_FAILED = 'GET_ALL_PENDING_TASKS_FAILED';
export const GET_ALL_PENDING_TASKS_SUCCESS = 'GET_ALL_PENDING_TASKS_SUCCESS';

// Error
export const REMOVE_ERROR = 'REMOVE_ERROR';