// Get all tasks
export const GET_ALL_TASKS_FAILED = 'GET_ALL_TASKS_FAILED';
export const GET_ALL_TASKS_REQ = 'GET_ALL_TASKS_REQ';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';

// Get all completed tasks
export const GET_ALL_COMPLETED_TASKS_REQ = 'GET_ALL_COMPLETED_TASKS_REQ';
export const GET_ALL_COMPLETED_TASKS_FAILED = 'GET_ALL_COMPLETED_TASKS_FAILED';
export const GET_ALL_COMPLETED_TASKS_SUCCESS = 'GET_ALL_COMPLETED_TASKS_SUCCESS';

// Get all pending tasks
export const GET_ALL_PENDING_TASKS_REQ = 'GET_ALL_PENDING_TASKS_REQ';
export const GET_ALL_PENDING_TASKS_FAILED = 'GET_ALL_PENDING_TASKS_FAILED';
export const GET_ALL_PENDING_TASKS_SUCCESS = 'GET_ALL_PENDING_TASKS_SUCCESS';

// Delete task
export const DELETE_TASK_REQ = 'DELETE_TASK_REQ';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';


// Error
export const REMOVE_ERROR = 'REMOVE_ERROR';