// Add Task
export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_FAILED = 'ADD_TASK_FAILED';
export const ADD_TASK_SUCCESS = 'ADD_TASK_SUCCESS';

// Delete Task
export const DELETE_TASK_REQUEST = 'DELETE_TASK_REQUEST';
export const DELETE_TASK_FAILED = 'DELETE_TASK_FAILED';
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS';

// Mark as completed
export const MARK_COMPLETED_REQUEST = 'MARK_COMPLETED_REQUEST';
export const MARK_COMPLETED_FAILED = 'MARK_COMPLETED_FAILED';
export const MARK_COMPLETED_SUCCESS = 'MARK_COMPLETED_SUCCESS';

// Get all tasks
export const GET_ALL_TASKS_REQUEST = 'GET_ALL_TASKS_REQUEST';
export const GET_ALL_TASKS_FAILED = 'GET_ALL_TASKS_FAILED';
export const GET_ALL_TASKS_SUCCESS = 'GET_ALL_TASKS_SUCCESS';

// Get all completed tasks
export const GET_ALL_COMPLETED_TASKS_REQUEST = 'GET_ALL_COMPLETED_TASKS_REQUEST';
export const GET_ALL_COMPLETED_TASKS_FAILED = 'GET_ALL_COMPLETED_TASKS_FAILED';
export const GET_ALL_COMPLETED_TASKS_SUCCESS = 'GET_ALL_COMPLETED_TASKS_SUCCESS';

// Get all pending tasks
export const GET_ALL_PENDING_TASKS_REQUEST = 'GET_ALL_PENDING_TASKS_REQUEST';
export const GET_ALL_PENDING_TASKS_FAILED = 'GET_ALL_PENDING_TASKS_FAILED';
export const GET_ALL_PENDING_TASKS_SUCCESS = 'GET_ALL_PENDING_TASKS_SUCCESS';